import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  serverExternalPackages: ["bullmq", "ioredis"],
  transpilePackages: [
    "@superior-ai/core",
    "@superior-ai/ai-gateway",
    "@superior-ai/agents",
    "@superior-ai/creative",
    "@superior-ai/seo",
    "@superior-ai/sales",
    "@superior-ai/competitor",
    "@superior-ai/marketing",
    "@superior-ai/memory",
    "@superior-ai/tools",
    "@superior-ai/intelligence",
    "@superior-ai/security",
    "@superior-ai/brand",
    "@superior-ai/workspace",
    "@superior-ai/documents",
    "@superior-ai/research",
    "@superior-ai/design",
    "@superior-ai/support",
    "@superior-ai/product-lab",
    "@superior-ai/cx",
    "@superior-ai/db",
    "@superior-ai/crm",
    "@superior-ai/queue",
    "@superior-ai/auth",
    "@superior-ai/shared",
    "@superior-ai/social",
    "@superior-ai/billing",
    "@superior-ai/observability",
    "@superior-ai/audit",
    "@superior-ai/storage",
    "@superior-ai/cache",
  ],
};

export default nextConfig;
