import { selectAgentsForGrowthTask, buildCompanyOrgChart } from "./departments/council";
import { runSafeUrlAudit } from "./url-audit";

export interface OrchestratorInput {
  objective: string;
  mode?: "plan_only" | "execute_safe";
  region?: string;
  product?: string;
  audience?: string;
  competitorUrls?: string[];
  userId?: string;
  projectId?: string;
}

export interface OrchestratorResult {
  objective: string;
  mode: "plan_only" | "execute_safe";
  council: Array<{ name: string; department: string; mandate: string }>;
  orgChart: ReturnType<typeof buildCompanyOrgChart>;
  competitorAudits?: Awaited<ReturnType<typeof runSafeUrlAudit>>[];
  modelOutput?: string;
  modelUsed?: string;
  note: string;
}

function guessTaskType(objective: string): string {
  const o = objective.toLowerCase();
  if (/(campaign|launch|market)/.test(o)) return "campaign_from_oneliner";
  if (/(build|fix|bug|repo|code|deploy)/.test(o)) return "software_factory";
  if (/(budget|cost|spend)/.test(o)) return "budget_review";
  if (/(ticket|support|customer issue)/.test(o)) return "triage";
  return "growth_loop";
}

export async function runOrchestrator(input: OrchestratorInput): Promise<OrchestratorResult> {
  const mode = input.mode ?? "execute_safe";
  const taskType = guessTaskType(input.objective);
  const council = selectAgentsForGrowthTask(taskType);
  const orgChart = buildCompanyOrgChart();

  let competitorAudits: OrchestratorResult["competitorAudits"];
  if (mode === "execute_safe" && input.competitorUrls?.length) {
    competitorAudits = await Promise.all(input.competitorUrls.slice(0, 5).map((u) => runSafeUrlAudit(u)));
  }

  const result: OrchestratorResult = {
    objective: input.objective,
    mode,
    council: council.map((a) => ({ name: a.name, department: a.department, mandate: a.mandate })),
    orgChart,
    competitorAudits,
    note: "Council selected. Model execution skipped: OPENROUTER_API_KEY not configured.",
  };

  if (mode !== "execute_safe" || !process.env.OPENROUTER_API_KEY) return result;

  try {
    // Deliberately dynamic — agents shouldn't hard-require ai-gateway to build if it's ever removed.
    const gateway = await import("@superior-ai/ai-gateway");
    const key = process.env.OPENROUTER_API_KEY!;
    const validated = await gateway.configureAndValidate("openrouter", { apiKey: key, baseUrl: process.env.OPENROUTER_BASE_URL });
    if (!validated.ok) {
      result.note = `Model execution skipped: ${validated.message}`;
      return result;
    }
    const rolePrompt = council.map((a) => `- ${a.name} (${a.department}): ${a.mandate}`).join("\n");
    const completion = await gateway.handleChatCompletions({
      model: "auto",
      messages: [
        {
          role: "system",
          content: `You are coordinating this expert council for SUPERIOR AI:\n${rolePrompt}\nProduce a concrete, actionable plan. Do not invent metrics, test results, or completed actions — only propose next steps.`,
        },
        {
          role: "user",
          content: [
            `Objective: ${input.objective}`,
            input.product ? `Product: ${input.product}` : "",
            input.audience ? `Audience: ${input.audience}` : "",
            input.region ? `Region: ${input.region}` : "",
            competitorAudits?.length ? `Competitor audit results: ${JSON.stringify(competitorAudits)}` : "",
          ].filter(Boolean).join("\n"),
        },
      ],
    });
    result.modelOutput = completion.choices?.[0]?.message?.content;
    result.modelUsed = completion.model;
    result.note = "Plan generated by live model call via OpenRouter.";
  } catch (err) {
    result.note = `Model execution failed: ${err instanceof Error ? err.message : String(err)}`;
  }
  return result;
}
