/**
 * Brand Kit Export Pack
 * Builds a downloadable package: SVG marks, palette CSS, guidelines MD, manifest JSON.
 * No fabricated raster assets.
 */

import type { BrandSystem, LetterformConcept } from "./letterform";

export interface BrandKitFile {
  path: string;
  content: string;
  mime: string;
}

export interface BrandKitPack {
  brandName: string;
  files: BrandKitFile[];
  /** JSON string of the full pack for API download as application/json */
  manifest: Record<string, unknown>;
}

function cssTokens(system: BrandSystem): string {
  const lines = [
    `/* ${system.brandName} — design tokens (generated by SUPERIOR AI Brand Studio) */`,
    `:root {`,
  ];
  for (const p of system.palette) {
    const varName = p.role.replace(/\s+/g, "-").toLowerCase();
    lines.push(`  --color-${varName}: ${p.hex}; /* ${p.name} */`);
  }
  lines.push(`  --font-headline: ${system.concepts[0]?.typography.headline ?? "system-ui"}, sans-serif;`);
  lines.push(`  --font-body: ${system.concepts[0]?.typography.body ?? "system-ui"}, sans-serif;`);
  lines.push(`}`);
  lines.push("");
  lines.push(`.brand-mark { display: inline-block; }`);
  return lines.join("\n");
}

function guidelinesMd(system: BrandSystem): string {
  return [
    `# ${system.brandName} — Brand Guidelines (draft)`,
    ``,
    `Industry: ${system.industry}`,
    `Personality: ${system.personality.join(", ") || "—"}`,
    ``,
    `## Palette`,
    ...system.palette.map((p) => `- **${p.name}** (\`${p.hex}\`) — ${p.role}`),
    ``,
    `## Letterform concepts`,
    ...system.concepts.map(
      (c) =>
        `### ${c.name} (${c.style})\n${c.concept}\n\nConstruction: ${c.construction}\n\nUsage: ${c.usage.join("; ")}`
    ),
    ``,
    `## Wordmark`,
    system.wordmarkNotes,
    ``,
    `## Favicon / social`,
    system.faviconNotes,
    system.socialAvatarNotes,
    ``,
    `## Guide outline`,
    ...system.brandGuideOutline.map((x) => `- ${x}`),
    ``,
    `---`,
    `Generated by SUPERIOR AI. SVG marks are geometric constructions — not stock imagery.`,
  ].join("\n");
}

function conceptSvgFile(c: LetterformConcept): BrandKitFile {
  return {
    path: `marks/${c.style}-${c.initials.toLowerCase()}.svg`,
    content: c.svgMark,
    mime: "image/svg+xml",
  };
}

export function buildBrandKitPack(system: BrandSystem): BrandKitPack {
  const files: BrandKitFile[] = [
    {
      path: "README.md",
      content: guidelinesMd(system),
      mime: "text/markdown",
    },
    {
      path: "tokens.css",
      content: cssTokens(system),
      mime: "text/css",
    },
    {
      path: "system.json",
      content: JSON.stringify(system, null, 2),
      mime: "application/json",
    },
    ...system.concepts.map(conceptSvgFile),
  ];

  return {
    brandName: system.brandName,
    files,
    manifest: {
      brandName: system.brandName,
      industry: system.industry,
      fileCount: files.length,
      files: files.map((f) => ({ path: f.path, mime: f.mime, bytes: f.content.length })),
      createdAt: system.createdAt,
      note: "Client can zip these files for download. No binary raster URLs invented.",
    },
  };
}

/** Simple multi-file bundle as a single JSON download (zip optional client-side). */
export function exportBrandKitJson(system: BrandSystem): string {
  const pack = buildBrandKitPack(system);
  return JSON.stringify(
    {
      ...pack.manifest,
      files: pack.files,
    },
    null,
    2
  );
}
